### ISSUE TITLE
Not so much an issue, but wanted your opinion on a solution for Caddy

### ISSUE THREAD

**Issue by ghost** [XiaoliChan/RedCaddy#1]
Working on a project [evilgocaddy](https://github.com/stevesec/evilgocaddy) and wanted some advise on how you think it would best with Caddy as the frontend and interfacing with Evilginx2 on the backend..

Caddyfile can be found in conf/Caddyfile.template

Can't really seem to get it to work. Thought you might have an idea.

Thanks,
SteveSec

**Comment by XiaoliChan** [comment]
I think it is useless with caddy, don't think need to set the blacklist headers with the phishing pages.
