### ISSUE TITLE
Can't connect to the server according to your configuration?

### ISSUE THREAD

**Issue by AhrendsSchmidt** [XiaoliChan/RedCaddy#2]
Look at the generated run.sh, firewall rules
![image](https://github.com/XiaoliChan/RedCaddy/assets/33677393/c7024b57-c1e8-4dcf-bcdb-cded70b56137)
The first rule is written like this, my client cannot connect to the server, or is there something wrong with my eating method? ? Please advise

**Comment by XiaoliChan** [comment]
Please provide your `forward-chains` file.

**Comment by AhrendsSchmidt** [comment]
Following your example, write，And I am using a legal certificate. When I use your code to generate an error, and the machine cannot go online, I give up this method

**Comment by XiaoliChan** [comment]
I need you forward-chains file to figure out what going on.
